[build]
  command = "npm run functions-install && npm run build"
  publish = "build"
  functions = "functions"

[dev]
  framework = "create-react-app"
  targetPort = 3000

[context.production.environment]
  NODE_VERSION = "18.17.1"
  MONGODB_URI = "mongodb+srv://jlimaaraujo:Kp6SJKnGF7dxjK21@cluster0.xujacgq.mongodb.net/" # Set this in Netlify's environment variables
  MONGODB_DB_NAME = "sample_mflix" 
  MONGODB_COLLECTION_NAME = "movies"
  MONGODB_COMMENTS_COLLECTION=comments

[build.environment]
  CI = "false"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[functions]
  node_bundler = "esbuild"
  
  [functions.settings]
    external_node_modules = ["mongodb"]
  
  [functions.timeout]
    timeout = 30 # seconds