[build]
  command = "npm run build"
  publish = "build"
  functions = "functions"

[dev]
  framework = "create-react-app"
  targetPort = 3000

[context.production.environment]
  NODE_VERSION = "18.17.1"  # Match your local Node version

[build.environment]
  CI = "false"